version: "3"

services:
  app:
    build: .  # Defina aqui o caminho para o contexto de build, neste caso, é o diretório atual onde o arquivo docker-compose.yml está localizado.
    depends_on:
      - redis
    links:
      - redis
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      NODE_ENV: dev  # Corrigido para NODE_ENV (em maiúsculas e com underscore)
      PORT: 3000
  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: easy4u
