name: Build and deploy Node.js app to Azure Web App - backend-easy4u

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: List archives
        run: ls

      - name: Install dependencies
        run: npm install --force
        working-directory: back-end

      - name: Zip artifact for deployment
        run: zip release.zip back-end/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./back-end

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'backend-easy4u'
          slot-name: 'Production'
          package: ./back-end
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC6549F3B20342A3B95BCF65FC00FDB0 }}
